export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const START_DOWNLOAD_TASKS = 'START_DOWNLOAD_TASKS';
export const DOWNLOAD_TASKS_SUCCESS = 'DOWNLOAD_TASKS_SUCCESS';
export const DOWNLOAD_TASKS_ERROR = 'DOWNLOAD_TASKS_ERROR';

export const GET_TASK_DELETE = 'GET_TASK_DELETE';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_ERROR = 'GET_TASK_ERROR';