export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const START_DOWNLOAD_TASKS = 'START_DOWNLOAD_TASKS';
export const DOWNLOAD_TASKS_SUCCESS = 'DOWNLOAD_TASKS_SUCCESS';
export const DOWNLOAD_TASKS_ERROR = 'DOWNLOAD_TASKS_ERROR';

export const GET_TASK_DELETE = 'GET_TASK_DELETE';
export const TASK_DELETED_SUCCESS = 'TASK_DELETED_SUCCESS';
export const TASK_DELETED_ERROR = 'TASK_DELETED_ERROR';

export const GET_TASK_EDIT = 'GET_TASK_EDIT';
export const START_EDITION_TASK = 'START_EDITION_TASK';
export const TASK_EDITED_SUCCESS = 'TASK_EDITED_SUCCESS';
export const TASK_EDITED_ERROR = 'TASK_EDITED_ERROR';